services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_DB=docker_nestjs
      - POSTGRES_PASSWORD=40304030

  pgAdmin:
    image: dpage/pgadmin4:6.14
    restart: always
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Lvrp1383